  SELECT * 
	FROM VEMSER_CASSIA.PAIS
ORDER BY NOME DESC;

SELECT 	LOGRADOURO, CEP
FROM	VEMSER_CASSIA.ENDERECO
WHERE	UPPER (LOGRADOURO) LIKE 'A%';

SELECT  *
FROM 	VEMSER_CASSIA.ENDERECO 
WHERE 	TRIM(CEP) LIKE '%0';

SELECT *
FROM   VEMSER_CASSIA.ENDERECO
WHERE  NUMERO BETWEEN 1 AND 100;

SELECT   *
FROM   	 VEMSER_CASSIA.ENDERECO
WHERE  	 LOGRADOURO LIKE 'RUA%'
ORDER BY CEP DESC;

SELECT COUNT(ID_ENDERECO)
FROM   VEMSER_CASSIA.ENDERECO

SELECT 	 COUNT(ID_ENDERECO)
FROM 	 VEMSER_CASSIA.ENDERECO
GROUP BY ID_CIDADE

